name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --release --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --release --verbose
